### ISSUE TITLE
Supporting target like "x86_64-poky-linux" in `build.rs` 

### ISSUE THREAD

**Issue by oqu** [koutheir/selinux-sys#1]
`build.rs` verify if the target is supported by checking if the target contains "-linux-" : https://github.com/koutheir/selinux-sys/blob/master/build.rs#L17

I am building a linux distribution with yocto and the target is something like "x86_64-poky-linux". Because of that, the file "selinux-sys.rs" is not generated and I cannot use the selinux crate.

What do you think about changing:
```rs
if !target.contains("-linux-") || target.ends_with("-kernel") {
  return; // Nothing to build for this architecture.
}
```
to 
```rs
if !target.contains("-linux") || target.ends_with("-kernel") {
  return; // Nothing to build for this architecture.
}
```

**Comment by koutheir** [comment]
@oqu, version `0.5.2` should solve this issue. Can you please let me know whether it does or not?

**Comment by oqu** [comment]
Thanks for being so reactive.
I just tested it and it works!
